# Generated by Django 2.1.5 on 2020-01-15 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_auto_20200115_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('setar_nfe', 'Alterar status NFE'), ('ver_dashboard', 'Visualizar Dashboard'))},
        ),
    ]
