# Generated by Django 2.1.5 on 2020-01-15 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_auto_20200108_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('deletar_clientes', 'Deletar Clientes'),)},
        ),
    ]
